name: site_webdev

author: Dart Team <misc@dartlang.org>
homepage: https://webdev.dartlang.org

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dev_dependencies:
  build_runner: any
  code_excerpter:
    git: https://github.com/chalin/code_excerpter.git
