name: site_webdev

author: Dart Team <misc@dartlang.org>
homepage: https://webdev.dartlang.org

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dev_dependencies:
  build_runner: any
  code_excerpt_updater: any
  code_excerpter: any
  linkcheck: '>=2.0.0-dev'
  # stagehand: ^2.0.0 # Not currently used

dependency_overrides:
  code_excerpt_updater:
    git: https://github.com/chalin/code_excerpt_updater.git
  code_excerpter:
    git: https://github.com/chalin/code_excerpter.git
    # path: ../code_excerpter
  linkcheck:
    git:
      url: https://github.com/chalin/linkcheck.git
      ref: chalin-dart-2-runtime-0612
