name: component_styles
description: Component Styles example
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular: ^5.3.0

dev_dependencies:
  build_runner: ^1.3.3
  build_test: ^0.10.7
  build_web_compilers: ^2.1.0
