name: api_docs
description: >
  Pubspec used to fetch specific versions of packages for the purpose of generating API docs,
  and for checking if new versions are available (see gulp/pkg-vers.js).
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  angular: ^5.0.0-beta+3
  angular_components: ^0.9.0-beta+2
  angular_forms: ^2.0.0-beta+3
  angular_router: ^2.0.0-alpha+18
  angular_test: ^2.0.0-beta+3

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0

