name: fetch_data_example
description: Fetch data example
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.64.2 <3.0.0'

dev_dependencies:
  build_runner: ^0.8.10
  build_web_compilers: ^0.4.0
  test: ^1.0.0
#  dartlang_examples_util:
#    git:
#      url: https://github.com/dart-lang/site-www.git
#      path: examples/util
