name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular: ^5.3.0

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  angular_test: ^2.3.0
  # #docregion build-dependencies
  build_runner: ^1.3.3
  build_test: ^0.10.7
  build_web_compilers: ^2.1.0
  # #enddocregion build-dependencies
  test: ^1.6.3
# #enddocregion dev_dependencies
